### ISSUE TITLE
Clone的最新的项目,跑不起来

### ISSUE THREAD

**Issue by lydlovezjr** [leotyndale/EnFloatingView#17]
<img width="717" alt="微信截图_20200721153746" src="https://user-images.githubusercontent.com/19246347/88026279-3554ab00-cb68-11ea-877b-5598228234ef.png">

**Comment by leotyndale** [comment]
可以clean或删除build目录重试下

**Comment by lydlovezjr** [comment]
chean,删除了也不行

**Comment by lydlovezjr** [comment]
删除重新clone的项目一样的报错,还是跑不起来
As版本4.0.1

**Comment by MIkeeJY** [comment]
As版本4.1.1 也一样  // compile 'com.imuxuan:floatingview:1.0' duplicate in library
引用重复了 手动把库的gradle注释掉即可

**Comment by leotyndale** [comment]
@MIkeeJY @lydlovezjr 
Please wait for a moment, 我一会看下

**Comment by MIkeeJY** [comment]
@leotyndale 就是引用库的gradle 又依赖maven库的代码了 引用重复导致的

**Comment by leotyndale** [comment]
> @leotyndale 就是引用库的gradle 又依赖maven库的代码了 引用重复导致的

👍 👍 👍 Sorry之前改代码调试的时候加入的，忘记注释掉了，已更新
