### ISSUE TITLE
使用崩溃了,佬.调用如下,崩溃如下

### ISSUE THREAD

**Issue by lydlovezjr** [leotyndale/EnFloatingView#18]
<img width="509" alt="微信截图_20200723170719" src="https://user-images.githubusercontent.com/19246347/88269767-36700e80-cd07-11ea-9aee-2959dc9305ee.png">
<img width="773" alt="微信截图_20200723170733" src="https://user-images.githubusercontent.com/19246347/88269770-3708a500-cd07-11ea-9978-0a1c8c59745e.png">

**Comment by lydlovezjr** [comment]
<img width="458" alt="微信截图_20200723171147" src="https://user-images.githubusercontent.com/19246347/88270040-9d8dc300-cd07-11ea-9293-9cb3dab2d29f.png">

**Comment by leotyndale** [comment]
自定义布局中需要定义悬浮窗icon的id为icon，可暂时用这个方案

后续会处理此bug

**Comment by lydlovezjr** [comment]
定义悬浮窗icon的id为icon,这什么意思啊,佬

**Comment by leotyndale** [comment]
> 定义悬浮窗icon的id为icon,这什么意思啊,佬

将你layout中的imageview的id设置为"@+id/icon"
