### ISSUE TITLE
使用转场动画bug

### ISSUE THREAD

**Issue by TianGuisen** [leotyndale/EnFloatingView#21]
startActivity(intent, ActivityOptions.makeSceneTransitionAnimation(this).toBundle())

返回的时候生命周期跟普通转场不同，导致按钮消失

**Comment by leotyndale** [comment]
目前暂无较好的解决方案，建议做延迟处理

**Comment by LeeeeeYao** [comment]
这个问题有好的解决方案吗，我也遇到当页面跳转有共享元素转场时，再次返回，悬浮窗消失了
