### ISSUE TITLE
点击有时候会触发 ANR

### ISSUE THREAD

**Issue by MenShengSeLang** [leotyndale/EnFloatingView#22]
ANR Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 32. Wait queue head age: 5595.0ms.)

android.os.MessageQueue.nativePollOnce(Native Method)

**Comment by leotyndale** [comment]
需要补充完整机型信息和更多信息，疑似复杂场景或低端机型影响
