### ISSUE TITLE
这个如果要改变悬浮窗的view，在特定Activity显示悬浮窗，并传入数据显示在窗体内，应该调哪个方法呢

### ISSUE THREAD

**Issue by lofty14** [leotyndale/EnFloatingView#3]

**Comment by leotyndale** [comment]
目前没有开放View自定义的接口，只开放了设置icon的接口
如有需求，可以将项目checkout下来，修改EnFloatingView的布局文件及View
数据控制View显示和在特定Activity显示可以自行创建一个ViewController控制

**Comment by leotyndale** [comment]
后面会将该功能需求实现

**Comment by Gennki** [comment]
你好，我尝试在特定的Activity的onCreate方法中attach并且在onDestory中detach，可以解决你的问题。
另外如果要改变悬浮窗的View，如果只是设置除了icon以外的图片的话，可以尝试这样写
```
EnFloatingView enFloatingView = FloatingView.get().getView();
ImageView icon = enFloatingView .findViewById(com.imuxuan.floatingview.R.id.icon);
Glide.with(activity).load(url).into(icon);
```

**Comment by Gennki** [comment]
@lofty14 希望对你有所帮助
