### ISSUE TITLE
这样会崩溃

### ISSUE THREAD

**Issue by yu1441** [leotyndale/EnFloatingView#31]
val iv = ImageView(this)
iv.setImageResource(R.mipmap.net_status1)
val fmv = FloatingMagnetView(this)
fmv.addView(iv)
//这样会崩溃
FloatingView.get().add()
FloatingView.get().view.removeAllViews()
FloatingView.get().view.addView(iv)
//这样会添加一屏幕的悬浮窗
FloatingView.get().add()
FloatingView.get().customView(fmv)
//这样会没有任何效果
FloatingView.get().customView(fmv).add()
//研究半天，要放自己图片，要这样。
FloatingView.get().icon(R.mipmap.net_status1).add()
//切换还得先remove

FloatingView.get().listener//点击事件也没有成功回调

**Comment by leotyndale** [comment]
md说明文档里一直都有做相关说明，类似如下：


4.设置悬浮窗icon

`FloatingView.get().icon(R.drawable.XXXXX);`

不知道是什么原因造成你走这么多弯路，是文档太难阅读？
