### ISSUE TITLE
如何在某个activity隐藏

### ISSUE THREAD

**Issue by mimishen** [leotyndale/EnFloatingView#6]
可以在相应activity内重写onStart和onStop覆盖掉悬浮窗的方法，或者在baseActivity加标记位，子类重写等都可以，有很多种方法。。。。大佬说一种吧，都试了不行呢。。。

**Comment by xuyingke** [comment]
你可以在 FloatingView 中添加数组，存储需要被隐藏的页面的类名？或者其他的标识。每次 attach 都判断是不是数组中的页面，是就隐藏。
