### ISSUE TITLE
悬浮球在应用中只能移动一小部分

### ISSUE THREAD

**Issue by ok406lhq** [leotyndale/EnFloatingView#8]
![image](https://user-images.githubusercontent.com/22291214/67189923-aa505400-f421-11e9-9b1c-5bcfe449a813.png)
悬浮窗在App中显示只显示在红色边框的范围内

**Comment by leotyndale** [comment]
看起来像是布局的问题，现在fix了吗

**Comment by ok406lhq** [comment]
> 看起来像是布局的问题，现在fix了吗

还是会这样，我再demo里边是正常显示的，到了游戏里边就出现这个问题了额。。

**Comment by leotyndale** [comment]
能发一下打开布局边界查看器后的截图吗

**Comment by BraverWang** [comment]
> ![image](https://user-images.githubusercontent.com/22291214/67189923-aa505400-f421-11e9-9b1c-5bcfe449a813.png)
> 悬浮窗在App中显示只显示在红色边框的范围内

请问游戏是Unity开发的吗 我这边也遇到这个问题 用setX setY好像没有刷新布局 使用requestLayout();可以解决显示范围问题 但移动过程中还是会有视图裁剪

**Comment by ok406lhq** [comment]
> > ![image](https://user-images.githubusercontent.com/22291214/67189923-aa505400-f421-11e9-9b1c-5bcfe449a813.png)
> > 悬浮窗在App中显示只显示在红色边框的范围内
> 
> 请问游戏是Unity开发的吗 我这边也遇到这个问题 用setX setY好像没有刷新布局 使用requestLayout();可以解决显示范围问题 但移动过程中还是会有视图裁剪

谢谢，这样子好多了 ^_^ 我是搞sdk开发的，需要在游戏中接入sdk。

**Comment by llyRayYoung** [comment]
我也遇到这个问题，请问有有更好的解决办法吗？requestLayout()好像不怎么好用 ，松开以后，好像会消失看不见
